### ISSUE TITLE
Get investigations by project id is not working properly, please fix

### ISSUE THREAD

**Issue by JoshuaVSherman** [NGS2Montage/montage#16]
Investigation List
GET /api/investigations/?project=2
HTTP 200 OK
Allow: GET, POST, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept

[
    {
        "analysis": [],
        "experiments": [],
        "hypotheses": [],
        "investigation_status": {
            "name": "Awesome",
            "description": "This investigation is totally awesome!"
        },
        "mechanisms": [],
        "models": [],
        "name": "Looking Really Hard",
        "project": 4,
        "theories": [],
        "id": 1,
        "created_by": "joshua",
        "modified_by": "joshua",
        "date_created": "2017-10-12T14:46:59.375052Z",
        "last_modified": "2017-10-12T14:46:59.375113Z"
    }
]

**Comment by nwself** [comment]
I added the ability to filter investigations by project although you can also get the list of investigations from the project object:

```
http://localhost:8000/api/projects/
[
    {
        "name": "Project A",
        "description": "This project is all about foobar",
        "team": {
            "name": "DAC",
            "description": "Discovery Analytics Center",
            "location": "VT",
            "website": "VT",
            "affiliation": "VT",
            "created_by": "admin",
            "modified_by": "admin",
            "id": 1,
            "date_created": "2017-10-11T03:35:38.225970Z",
            "last_modified": "2017-10-11T03:35:38.225999Z"
        },
        "project_state": {
            "name": "READY",
            "description": "State for ready things"
        },
        "investigations": [
            "http://localhost:8000/api/investigations/1/",
            "http://localhost:8000/api/investigations/2/",
            "http://localhost:8000/api/investigations/3/"
        ],
        "id": 1,
        "created_by": "admin",
        "modified_by": "admin",
        "date_created": "2017-10-11T03:35:57.258663Z",
        "last_modified": "2017-10-11T03:35:57.258696Z"
    }
]
```
