### ISSUE TITLE
Project is missing the name attribute, please add that to the model

### ISSUE THREAD

**Issue by JoshuaVSherman** [NGS2Montage/montage#27]
{
    "description": "whatever",
    "team": {
        "name": "Testing Team",
        "description": "Team for testing",
        "location": "The cloud",
        "website": "dac.cs.vt.edu",
        "affiliation": "VT",
        "created_by": "admin",
        "modified_by": "admin",
        "id": 1,
        "date_created": "2017-09-11T16:05:19.722000Z",
        "last_modified": "2017-09-11T16:05:19.722000Z"
    },
    "project_state": {
        "name": "READY",
        "description": "State for ready things"
    },
    "investigations": [],
    "id": 7,
    "created_by": "joshua",
    "modified_by": "joshua",
    "date_created": "2017-10-10T16:37:02.262164Z",
    "last_modified": "2017-10-10T16:37:02.262316Z"
}

**Comment by nwself** [comment]
Done. Make sure to run `./manage.py migrate` to update the DB.
